---
- name: Fix host name
  hosts: all
  gather_facts: false
  become: yes
  tasks:
  - debug:
      msg: "{{ inventory_hostname }}"
  - name: Fix host name
    hostname:
      name: "{{ inventory_hostname }}"
