---
- name: Create Topology Using Vagrant
  hosts: localhost
  gather_facts: false
  roles:
      - benthomasson.vagrant_tools
  tasks:
    - vagrant_up:
    - vagrant_ssh_config:
        output: ssh-config
    - convert_ssh_config_to_ansible_inventory2:
        data: topology.yml
        ssh_config: ssh-config
        output: hosts
